import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import Navigation from '@/components/navigation';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next Demo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen flex flex-col`}
        >
          <header className="bg-white shadow-sm border-b border-gray-200">
            <Navigation />
          </header>
          <main className="max-w-4xl mx-auto px-4 py-4 flex-1 w-full">
            {children}
          </main>
          <footer className="text-center py-4 text-gray-500 text-sm border-t border-gray-200">
            <p>&copy; {new Date().getFullYear()} My Application</p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
